export interface NewsResponse {
    status:       string;
    totalResults: number;
    articles:     Article[];
}

// Generated by https://quicktype.io
export interface NewsResponse {
    status:       string;
    totalResults: number;
    articles:     Article[];
}

export interface Article {
  source: {
    id: string | null | undefined;
    name: string | null | undefined;
  };
  author?: string | null | undefined;
  title: string | null | undefined;
  description?: string | null | undefined;
  url: string | null | undefined;
  urlToImage?: string | null | undefined;
  publishedAt: string | null | undefined;
  content?: string | null | undefined;
}


export interface Source {
    id?:  string | undefined | null;
    name: string;
}


export interface ArticlesByCategoryAndPage {
  [category: string]: {
    page: number;
    articles: Article[];
  };
}

export enum ID {
    Techcrunch = "techcrunch",
}

export enum Name {
    TechCrunch = "TechCrunch",
}


